/// Flutter icons RelicIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RelicIcons
///      fonts:
///       - asset: fonts/RelicIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class RelicIcons {
  RelicIcons._();

  static const String _kFontFam = 'RelicIcons';
  // static const _kFontPkg = null;

  static const IconData search = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData cart = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData profile = IconData(0xe803, fontFamily: _kFontFam);
}
